# Generated by Django 2.1.7 on 2019-03-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_application_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='commitment',
            new_name='commitment_time',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='volunteeremail',
            new_name='volunteer_email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
