# Generated by Django 2.1.7 on 2019-03-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20190321_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='note',
            new_name='why_TFI',
        ),
    ]
