# Generated by Django 2.1.7 on 2019-03-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20190321_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
