# Generated by Django 2.1.7 on 2019-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_auto_20190321_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='opportunity_creator',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='opportunity_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
