# Generated by Django 2.1.7 on 2019-03-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_auto_20190322_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='why_TFI',
            field=models.TextField(max_length=250),
        ),
    ]
