# Generated by Django 2.1.7 on 2019-03-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fromday',
            new_name='from_day',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='today',
            new_name='to_day',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='useremail',
            new_name='user_email',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
