# Generated by Django 2.1.7 on 2019-03-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190321_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hours',
            new_name='commitment_needed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_email',
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='creator_email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
